development:
  adapter: postgresql
  encoding: unicode
  database: eventee_development
  pool: 5
  username: Acuna
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: eventee_test
  pool: 5
  username: Acuna
  password:
  host: localhost
