development:
  adapter: postgresql
  encoding: unicode
  database: eventee_development
  pool: 5
  username: rails_pg
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: eventee_test
  pool: 5
  username: rails_pg
  password: postgres
  host: localhost
